In [1]:
import numpy as np

In [9]:
np.random.random()  #random (0-1)

0.013403894311980746

In [12]:
np.random.seed(1)   # random same value again and again
np.random.random()

0.417022004702574

In [19]:
np.random.uniform(1,100)   #range

35.210511977261724

In [23]:
np.random.uniform(1,100,10).reshape(2,5)

array([[ 2.81053946, 75.26428718, 98.8972478 , 75.06839978, 28.76395521],
       [79.13865352, 11.21937465, 45.34145909, 90.95095481, 30.06780069]])

In [34]:
np.random.randint(1,100,15).reshape(3,5)   #integer in given range

array([[18, 43, 21, 49, 23],
       [14, 98, 54, 85, 11],
       [97, 56, 62, 57, 90]], dtype=int32)

In [36]:
a=np.random.randint(1,10,6)
a

array([5, 7, 9, 9, 3, 8], dtype=int32)

In [37]:
np.max(a)

np.int32(9)

In [38]:
np.min(a)

np.int32(3)

In [41]:
np.argmax(a)  #index of max value

np.int64(2)

In [44]:
np.argmin(a)  #index of min value

np.int64(4)

In [50]:
a=np.random.randint(1,110,6)
a

array([41, 79, 46, 88, 17, 29], dtype=int32)

In [51]:
a[a%2==0] = -1
a

array([41, 79, -1, -1, 17, 29], dtype=int32)

In [53]:
a=np.random.randint(1,15,6)
a

array([14,  2,  3,  5,  4,  1], dtype=int32)

In [57]:
np.where(a%2==1,-1,a) # if condition true return a otherwise it return false

array([14,  2, -1, -1,  4, -1], dtype=int32)

In [59]:
a=np.random.randint(1,50,10)
a

array([33,  9, 21, 14, 16, 42,  1, 45, 20, 25], dtype=int32)

In [60]:
np.sort(a)

array([ 1,  9, 14, 16, 20, 21, 25, 33, 42, 45], dtype=int32)

In [62]:
np.percentile(a,25)

np.float64(14.5)

In [64]:
np.percentile(a,50)

np.float64(20.5)

In [65]:
np.percentile(a,100)

np.float64(45.0)