In [4]:
# Creating Numpy/ n-d array

import numpy as np

In [9]:
arr1 = np.array([1,2,3,4,5,6,7])
print(arr1)

[1 2 3 4 5 6 7]


In [10]:
arr1.shape

(7,)

In [11]:
arr1.dtype

dtype('int64')

In [12]:
arr1.itemsize   # bcoz float

8

In [13]:
arr1.ndim

1

In [14]:
arr2 = np.array([[1,2,3,4], [4,5,6,7]])
print(arr2)

[[1 2 3 4]
 [4 5 6 7]]


In [15]:
arr2.shape

(2, 4)

In [16]:
arr2.size

8

In [17]:
arr2.dtype

dtype('int64')

In [18]:
arr3 = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
arr3.dtype

dtype('int64')

In [20]:
arr3.ndim

2

In [21]:
arr4=np.zeros((2,3))
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
arr4=np.ones((3,3))
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
arr14=np.identity((5))
print(arr14)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
arr14.dtype

dtype('float64')

In [25]:
arr14.astype('int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [26]:
arr4=np.arange(12)
print(arr4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [27]:
arr41=np.linspace(10,20,10) #lower, upper
print(arr41)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [28]:
arr41.astype('int')

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 20])

In [29]:
arr4=arr3.copy() 
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
arr10 = np.array([[[1,2],[4,3]], [[5,6],[8,9]]])
print(arr10)

[[[1 2]
  [4 3]]

 [[5 6]
  [8 9]]]


In [31]:
arr10.shape

(2, 2, 2)

In [32]:
arr10.ndim

3

In [33]:

list1=range(100)
print(list1)
list1n=np.arange(100)

range(0, 100)


In [34]:
import sys

In [35]:
print(sys.getsizeof((1)*len(list1)))  # list  #size=2800

28


In [36]:
print(list1n.itemsize*list1n.size)  #numpy  #size = 800

800


In [1]:
import time   #list

In [6]:
x=range(100000)
y=range(100000,200000)

start_time=time.time() 

c=[(x,y) for x,y in zip(x,y)]

print(time.time()-start_time)

0.013923883438110352


In [5]:
a=np.arange(100000)
b=np.arange(100000,200000)

start_time=time.time()
c=a+b

print(time.time()-start_time)

0.0036215782165527344


In [14]:
arrX=np.arange(24).reshape(6,4)
print(arrX)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [22]:
arrX[4:6,2:4]

array([[18, 19],
       [22, 23]])

In [23]:
arrX[2:3,2:3]

array([[10]])

In [24]:
for i in arrX:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [26]:
for i in np.nditer(arrX):
    print(i,end="  ")

0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  