<a href="https://colab.research.google.com/github/ran732/python-Libraries/blob/main/Numpy/Numpy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is numpy?

```
# This is formatted as code
```


**NumPy** is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

## **Numpy Arrays Vs Python Sequences**

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [ ]:
#np.array
import numpy as np

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
#2D and 3D

b = np.array([[1,2,3],[4,5,7]])
print(b)


[[1 2 3]
 [4 5 7]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[4,5],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[4 5]
  [7 8]]]


In [ ]:
# d type
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

In [ ]:
np.array([1,2,3,4],dtype=bool)

array([ True,  True,  True,  True])

In [ ]:
np.array([1,2,3,4],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [ ]:
#np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
 # np.reshape
 np.arange(1,9).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
#np.ones and np.zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.random
np.random.random((3,4))

array([[0.15879944, 0.90648699, 0.40010061, 0.60836671],
       [0.93690045, 0.7782348 , 0.10568259, 0.50551063],
       [0.5482716 , 0.89167004, 0.32414703, 0.21523379]])

In [ ]:
#np.linspace
np.linspace(-10,10,10)  #equidistance point generator in given range

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
#np.identity
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# **Numpy Attributes**

In [ ]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a2


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
#ndim
a3.ndim

3

In [ ]:
#shape
a3.shape


(2, 2, 2)

In [ ]:
#size
a3.size

8

In [ ]:
#itemsize
a3.itemsize

8

In [ ]:
#dtype
a2.dtype

dtype('float64')

# **Changing Datatypes**

In [ ]:
#astype
#reduce size
a2.astype(np.int32)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

In [ ]:
a2.itemsize

8

# **Array Operations**

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#scalar operations

#arithmatic ( +,-,*,/,%)
a1 % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [ ]:
#relational (>,<,>=,<=,!=)
a1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#vector operations

# arithmatic
a2 + a1  #squre matrix must be

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# **Array Functions**

In [ ]:
a1= np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[79.,  5., 61.],
       [64., 15., 19.],
       [19., 90., 13.]])

In [ ]:
#max/min/sum/prod/
# 0--> col and 1--> row
np.max(a1)
np.max(a1,axis=0)

array([79., 90., 61.])

In [ ]:
np.min(a1)
np.min(a1,axis=0)

array([19.,  5., 13.])

In [ ]:
np.sum(a1)

np.float64(365.0)

In [ ]:
np.prod(a1)

np.float64(9769924944000.0)

In [ ]:
# mean/median/std/var
np.mean(a1)
np.var(a1,axis=1)

array([ 992.88888889,  493.55555556, 1222.88888889])

In [ ]:
#trigonomatry functions
np.sin(a1)

array([[-0.44411267, -0.95892427, -0.96611777],
       [ 0.92002604,  0.65028784,  0.14987721],
       [ 0.14987721,  0.89399666,  0.42016704]])

In [ ]:
 # dot product (3,4 . 4,2 = 3,2)

 a2=np.arange(12).reshape(3,4)
 a3=np.arange(12,24).reshape(4,3)
 np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#log and exponents
np.log (a1)

array([[4.36944785, 1.60943791, 4.11087386],
       [4.15888308, 2.7080502 , 2.94443898],
       [2.94443898, 4.49980967, 2.56494936]])

In [ ]:
np.exp(a1)

array([[2.03828107e+34, 1.48413159e+02, 3.10429794e+26],
       [6.23514908e+27, 3.26901737e+06, 1.78482301e+08],
       [1.78482301e+08, 1.22040329e+39, 4.42413392e+05]])

In [ ]:
#round/floor/cell
# round -- > convert into nearest integer
#floor -- > back integer
#ceil -- > front integer

np.ceil(np.random.random((2,3))*100)

array([[49., 80., 77.],
       [96., 51., 88.]])

# **Indexing and Slicing**

In [ ]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(27).reshape(3,3,3)

a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a2[0]  # row
a2[0][2] # row , col
a2[0,2]  # row , col

np.int64(2)

In [ ]:
a3[1,0,1]   #5
a3[0,1,0]   #2
a3[1,1,1]   #7

np.int64(7)

In [ ]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1[2:5]  #2,3,4
a1[2:5:2]

array([2, 4])

In [ ]:
a2[0,:]
a2[:,2]
a2[1,1:] #5,6,7
a2[2,1:3] #9,10
a2[::2,::3] #0,3,8,11
a2[::2,1::2] #1,3,9,11
a2[1,::3]#4,7
a2[:2,1:] #1,2,3,5,6,7



array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1,] #
a3[0::2]
a3[0,1,:] #3,4,5
a3[1,:,1] #10,13,16
a3[2,1:,1:] #22,23,25,26
a3[::2, 0,::2] #0,2,18,22

array([[ 0,  2],
       [18, 20]])

# **Iterating**

In [ ]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i, end =' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

# **Reshaping**

In [ ]:
#reshape

Transpose concert row into col and vice-versa


In [ ]:
# tranpose
np.transpose(a2)
a2.T # sort m hhaa🙃

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

ravel convert higher dimention to 1D array

In [ ]:
#ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# **Stacking**  : add krna


In [ ]:

a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# horizontal stacking
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [ ]:
# vertical stacking
np.vstack((a4,a5,a4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# **Splitting**  : opposite of stacking

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# horizontal splitting

np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
# vertical splitting

np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]