In [1]:
import numpy as np

In [2]:
arr1=np.array([1,12,3,4,24,54])
arr2=np.array([5,2,74,8,4,5])

In [3]:
print(arr2-arr1)

[  4 -10  71   4 -20 -49]


In [4]:
print(arr2*arr1)

[  5  24 222  32  96 270]


In [5]:
print(arr2*2)

[ 10   4 148  16   8  10]


In [6]:
print(arr1>5)

[False  True False False  True  True]


In [7]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)


In [10]:
print(arr3.dot(arr4))

[[ 28  31]
 [100 112]]


In [11]:
print(arr1.dot(arr2))

649


In [18]:
print((arr4))

[[ 6  7]
 [ 8  9]
 [10 11]]


In [21]:
print((arr4).max(axis=1))

[ 7  9 11]


In [15]:
print((arr4).min())

6


In [22]:
print(arr4.sin())

AttributeError: 'numpy.ndarray' object has no attribute 'sin'

In [23]:
print(arr4.ndim)

2


In [25]:
print(arr4.ravel())

[ 6  7  8  9 10 11]


In [26]:
print(arr4)

[[ 6  7]
 [ 8  9]
 [10 11]]


In [27]:
print(arr4.transpose())

[[ 6  8 10]
 [ 7  9 11]]


In [28]:
print(arr3)

[[0 1 2]
 [3 4 5]]


In [29]:
arr5=np.arange(12,18).reshape(2,3)
print(arr5)

[[12 13 14]
 [15 16 17]]


In [32]:
print(np.hstack((arr3,arr5)))

[[ 0  1  2 12 13 14]
 [ 3  4  5 15 16 17]]


In [33]:
print(np.vstack((arr3,arr5)))

[[ 0  1  2]
 [ 3  4  5]
 [12 13 14]
 [15 16 17]]


In [41]:
print(np.vsplit(arr3,2))

[array([[0, 1, 2]]), array([[3, 4, 5]])]


In [42]:
import numpy  as np

In [66]:
arr=np.random.randint(low=1,high=100,size=20).reshape(4,5)
print(arr)

[[13  1 85 22 18]
 [95 21 88 15 44]
 [87 72 78 61 23]
 [57 43 34 94 13]]


In [48]:
print(arr[0])

[48 38  2 16 87]


In [49]:
print(arr[2])

[49 37 46 28  4]


In [51]:
print(arr[1][2])  #14

14


In [52]:
print(arr[3][3])

7


In [55]:
print(arr[arr>50])

[87 98 64 69]


In [68]:
print(arr[(arr>50) & (arr%2==0)])

[]
